# Generated by Django 5.1.1 on 2025-04-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
