# Generated by Django 5.1.1 on 2025-04-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='in_cart',
        ),
    ]
